import { useState, useEffect, useRef, useCallback } from 'react'

const EMOJI_CATEGORIES: Record<string, string[]> = {
  'Smileys': ['😀','😃','😄','😁','😅','😂','🤣','😊','😇','🙂','😉','😌','😍','🥰','😘','😗','😙','😚','😋','😛','😜','🤪','😝','🤑','🤗','🤭','🤫','🤔','🤐','🤨','😐','😑','😶','😏','😒','🙄','😬','🤥','😔','😪','🤤','😴','😷','🤒','🤕','🤢','🤮','🥵','🥶','🥴','😵','🤯','🤠','🥳','😎','🤓','🧐','😕','😟','🙁','😮','😯','😲','😳','🥺','😦','😧','😨','😰','😥','😢','😭','😱','😖','😣','😞','😓','😩','😫','🥱','😤','😡','😠','🤬','😈','👿','💀','☠️','💩','🤡','👹','👺','👻','👽','👾','🤖'],
  'Gestures': ['👋','🤚','🖐️','✋','🖖','👌','🤌','🤏','✌️','🤞','🤟','🤘','🤙','👈','👉','👆','🖕','👇','☝️','👍','👎','✊','👊','🤛','🤜','👏','🙌','👐','🤲','🤝','🙏','✍️','💅','🤳','💪','🦾','🦿','🦵','🦶','👂','🦻','👃','🧠','🫀','🫁','🦷','🦴','👀','👁️','👅','💋','🫦','🧑‍🤝‍🧑','👫','👭','👬','💏','💑','👪','🗣️','👤','👥','🧑‍🧑','🧑‍🧒'],
  'Animals': ['🐶','🐱','🐭','🐹','🐰','🦊','🐻','🐼','🐻‍❄️','🐨','🐯','🦁','🐮','🐷','🐸','🐵','🙈','🙉','🙊','🐒','🐔','🐧','🐦','🐤','🦆','🦅','🦉','🦇','🐺','🐗','🐴','🦄','🐝','🪱','🐛','🦋','🐌','🐞','🐜','🪰','🪱','🦟','🦗','🕷️','🦂','🐢','🐍','🦎','🦖','🦕','🐙','🦑','🦐','🦞','🦀','🐡','🐠','🐟','🐬','🐳','🐋','🦈','🐊','🐅','🐆','🦓','🦍','🦧','🦣','🐘','🦛','🦏','🐪','🐫','🦒','🦘','🦬','🐃','🐂','🐄','🐎','🐖','🐏','🐑','🦙','🐐','🦌','🐕','🐩','🦮','🐈','🐓','🦃','🦚','🦜','🦢','🦩','🕊️','🐇','🦝','🦨','🦡','🦫','🦦','🦥','🐁','🐀','🐿️','🦔'],
  'Nature': ['🌵','🎄','🌲','🌳','🌴','🪵','🌱','🌿','☘️','🍀','🎍','🎎','🪴','🎋','🍃','🍂','🍁','🪹','🍄','🌾','💐','🌷','🌹','🥀','🌺','🌸','🌼','🌻','🌞','🌝','🌛','🌜','🌚','🌕','🌖','🌗','🌘','🌑','🌒','🌓','🌔','🌙','🌎','🌍','🌏','🪐','💫','⭐','🌟','✨','⚡','🌪️','🌈','☀️','🌤️','⛅','🌥️','☁️','🌦️','🌧️','⛈️','🌩️','🌨️','❄️','☃️','⛄','🌬️','💨','🌫️','🌪️'],
  'Food': ['🍎','🍐','🍊','🍋','🍌','🍉','🍇','🍓','🫐','🍈','🍒','🍑','🥭','🍍','🥥','🥝','🍅','🍆','🥑','🥦','🥬','🥒','🌶️','🫑','🌽','🥕','🧄','🧅','🥔','🍠','🥐','🥯','🍞','🥖','🥨','🧀','🥚','🍳','🧈','🥞','🧇','🥓','🥩','🍗','🍖','🦴','🌭','🍔','🍟','🍕','🫓','🥪','🥙','🧆','🌮','🌯','🫔','🥗','🥘','🫕','🍝','🍜','🍲','🍛','🍣','🍱','🥟','🦪','🍤','🍙','🍚','🍘','🍥','🥠','🥮','🍢','🍡','🍧','🍨','🍦','🥧','🧁','🍰','🎂','🍮','🍭','🍬','🍫','🍿','🍩','🍪','🌰','🥜','🍯','🥛','🍼','🫖','☕','🍵','🧃','🥤','🧋','🍶','🍺','🍻','🥂','🍷','🥃','🍸','🍹','🧉','🍾','🧊'],
  'Activities': ['⚽','🏀','🏈','⚾','🥎','🎾','🏐','🏉','🥏','🎱','🪀','🏓','🏸','🏒','🏑','🥍','🏏','🪃','🥅','⛳','🪁','🏹','🎣','🤿','🥊','🥋','🎽','🛹','🛼','🛷','⛸️','🥌','🎿','⛷️','🏂','🪂','🏋️','🤼','🤸','🤺','⛹️','🤾','🏌️','🏇','🧘','🏄','🏊','🤽','🚣','🧗','🚵','🚴','🏆','🥇','🥈','🥉','🏅','🎖️','🏵️','🎗️','🎫','🎟️','🎪','🤹','🎭','🩰','🎨','🎬','🎤','🎧','🎼','🎹','🥁','🪘','🎷','🎺','🪗','🎸','🪕','🎻','🎲','♟️','🎯','🎳','🎮','🕹️','🎰'],
  'Objects': ['⌚','📱','📲','💻','⌨️','🖥️','🖨️','🖱️','🖲️','💽','💾','💿','📀','📼','📷','📸','📹','🎥','📽️','🎞️','📞','☎️','📟','📠','📺','📻','🎙️','🎚️','🎛️','🧭','⏱️','⏲️','⏰','🕰️','⌛','⏳','📡','🔋','🔌','💡','🔦','🕯️','🪔','🧯','🛢️','💸','💵','💴','💶','💷','🪙','💰','💳','💎','⚖️','🪜','🧰','🪛','🔧','🔨','⚒️','🛠️','⛏️','🪚','🔩','⚙️','🪤','🧱','⛓️','🧲','🔫','💣','🧨','🪓','🔪','🗡️','⚔️','🛡️','🚬','⚰️','🪦','⚱️','🏺','🔮','📿','🧿','💈','⚗️','🔭','🔬','🕳️','🩹','🩺','💊','💉','🩸','🧬','🦠','🧫','🧪','🌡️','🧹','🪠','🧺','🧻','🚽','🚰','🚿','🛁','🛀','🧼','🪥','🪒','🧽','🪣','🧴','🛎️','🔑','🗝️','🚪','🪑','🛋️','🛏️','🛌','🧸','🪆','🖼️','🪞','🪟','🛍️','🛒','🎁','🎈','🎏','🎀','🪄','🪅','🎊','🎉','🎎','🏮','🎐','🧧','✉️','📩','📨','📧','💌','📥','📤','📦','🏷️','📪','📫','📬','📭','📮','📯','📜','📃','📄','📑','🧾','📊','📈','📉','🗒️','🗓️','📆','📅','🗑️','📇','🗃️','🗳️','🗄️','📋','📁','📂','🗂️','🗞️','📰','📓','📒','📔','📕','📗','📘','📙','📚','📖','🔖','🧷','🔗','📎','🖇️','📐','📏','🧮','📌','📍','✂️','🖊️','🖋️','✒️','🖌️','🖍️','📝','✏️','🔍','🔎','🔏','🔐','🔒','🔓'],
  'Symbols': ['❤️','🧡','💛','💚','💙','💜','🖤','🤍','🤎','💔','❣️','💕','💞','💓','💗','💖','💘','💝','💟','☮️','✝️','☪️','🕉️','☸️','✡️','🔯','🕎','☯️','☦️','🛐','⛎','♈','♉','♊','♋','♌','♍','♎','♏','♐','♑','♒','♓','🆔','⚛️','🉑','☢️','☣️','📴','📳','🈶','🈚','🈸','🈺','🈷️','✴️','🆚','💮','🉐','㊙️','㊗️','🈴','🈵','🈹','🈲','🅰️','🅱️','🆎','🆑','🅾️','🆘','⛔','📛','🔞','🔃','🔄','🔙','🔛','🔝','✅','❎','🈯','💹','❇️','✳️','❎','✅','🆓','🌐','ℹ️','🈁','🔣','🔤','🔡','🔠','🆖','🆔','🆕','🆗','🆘','🆙','🆒','🆕','🆗'],
}

const EMOJI_KEYWORDS: Record<string, string[]> = {
  '😂': ['laugh','laughing','lol','funny','haha','lmao','tears','joy','rotfl'],
  '🤣': ['laugh','laughing','lol','funny','rolling on the floor'],
  '😀': ['smile','happy','grinning'],
  '😃': ['smile','happy','grinning','festive'],
  '😄': ['smile','happy','grinning','laugh'],
  '😁': ['smile','happy','grin'],
  '😅': ['nervous','sweat','relieved','awkward','sweating'],
  '😊': ['smile','happy','blush','cute','shy'],
  '🥰': ['love','heart','kissing','adore','hearts'],
  '😍': ['love','heart','eyes','adore','crush'],
  '😘': ['love','kiss','heart','blowing kiss'],
  '🥺': ['plead','puppy eyes','begging','sad','cute'],
  '😭': ['cry','crying','sad','tears','sob','bawling'],
  '😤': ['angry','triumph','huff','frustrated','mad'],
  '😡': ['angry','pout','mad','rage','furious'],
  '😠': ['angry','disappointed','grumpy','mad'],
  '🤬': ['angry','cursing','swear','curse','grawlix'],
  '🤯': ['mind blown','exploding','shock','crazy','wtf'],
  '😱': ['shock','scream','fear','surprised','surprised','oh no'],
  '😳': ['blush','flushed','embarrassed','shy','nervous'],
  '🥴': ['dizzy','woozy','tipsy','drunk','confused'],
  '🤪': ['crazy','weird','goofy','zany'],
  '🤑': ['money','rich','dollar','wealth'],
  '🤗': ['hug','embrace','warm','cuddle'],
  '🤭': ['giggle','gossip','tee hee','chatty'],
  '🤫': ['shush','quiet','hush','secret'],
  '🤐': ['zipper','mouth','quiet','secret','shut up'],
  '😐': ['neutral','meh','whatever',' Expressionless'],
  '😑': ['expressionless','deadpan','no expression'],
  '😬': ['grimace','awkward','nervous','yikes'],
  '🙄': ['eye roll','really','ugh','whatever'],
  '😒': ['unamused','bored','meh','displeased'],
  '😔': ['sad','pensive','down','unhappy','melancholy'],
  '😴': ['sleep','sleeping','tired','zzz','nap'],
  '🤢': ['sick','nauseous','vomit','gross','queasy'],
  '🤮': ['sick','vomit','puke','nausea','sick'],
  '🥵': ['hot','heat','sweating','fire','burning'],
  '🥶': ['cold','freezing','snow','brrr','icy'],
  '😵': ['dizzy','woozy','knocked out','fainted'],
  '🤠': ['cowboy','western','hat','yeehaw'],
  '🥳': ['party','celebrate','birthday','confetti','yay'],
  '🥸': ['disguise','mystery','nose','glasses','who','suit'],
  '😎': ['cool','sunglasses','chill','awesome','laid back'],
  '🤓': ['nerd','glasses','smart','geek','study'],
  '🧐': ['monocle','inspector','detective','curious'],
  '🤡': ['clown','funny','silly','fool'],
  '👻': ['ghost','boo','halloween','ghost'],
  '💀': ['skull','dead','death','halloween','bone'],
  '👽': ['alien','ufo','out of this world',' extraterrestrial'],
  '🤖': ['robot','bot','computer','machine','android'],
  '💩': ['poop','crap','turd','dung','silly'],
  '❤️': ['heart','love','red','romantic','red heart'],
  '🧡': ['heart','love','orange','warm','orange heart'],
  '💛': ['heart','love','yellow','yellow heart'],
  '💚': ['heart','love','green','green heart'],
  '💙': ['heart','love','blue','blue heart'],
  '💜': ['heart','love','purple','purple heart'],
  '🖤': ['heart','love','black','black heart'],
  '🤍': ['heart','love','white','white heart'],
  '🤎': ['heart','love','brown','brown heart'],
  '💔': ['heart','broken','break','sad','broke'],
  '❣️': ['heart','exclamation','love','punctuation'],
  '💕': ['heart','love','two hearts','pinky','romantic'],
  '💞': ['heart','revolving','love','sparkling heart'],
  '💓': ['heart','pulse','beating','heartbeat','love'],
  '💗': ['heart','growing','love','cute'],
  '💖': ['heart','sparkling','love','pink'],
  '💘': ['heart','cupid','arrow','love','romance'],
  '💝': ['heart','gift','love','present','valentine'],
  '💟': ['heart','decoration','sparkle','cute'],
  '☮️': ['peace','symbol','hippie','free','love'],
  '✝️': ['cross','christian','religion','faith'],
  '☪️': ['moon','crescent','islam','star','religion'],
  '🕉️': ['om','hindu','symbol','spiritual','buddhism'],
  '☸️': ['wheel','dharma','buddhism','peace','symbol'],
  '⚛️': ['atom','science','physics','chemistry','nuclear'],
  '🏳️': ['flag','white','peace','surrender'],
  '🏴': ['flag','black','mourning','anarchist'],
  '🔥': ['fire','hot','lit','flame','awesome','🔥','flames'],
  '💯': ['100','hundred','perfect','score','on fire'],
  '⚡': ['lightning','zap','electric','power','high voltage','electricity'],
  '🌈': ['rainbow','pride','LGBT','colorful','gay'],
  '⭐': ['star','rating','gold','favorite','yellow'],
  '🌟': ['star','glowing','sparkle','night','shining'],
  '✨': ['sparkle','sparkles','shiny','glitter','stars','excited'],
  '💫': ['dizzy','star','sparkle','surprised','confused'],
  '⚽': ['sports','soccer','football','ball','goal'],
  '🏀': ['sports','basketball','ball','hoop','game'],
  '🏈': ['sports','football','american','nfl','ball'],
  '⚾': ['sports','baseball','ball','mlb','game'],
  '🎾': ['sports','tennis','ball','game','racket'],
  '🏐': ['sports','volleyball','ball','game','bump'],
  '🎱': ['pool','billiards','ball','8 ball','game'],
  '🏓': ['sports','ping pong','table tennis','paddle','game'],
  '🎯': ['target','bullseye','dart','goal','aim','hit'],
  '🎮': ['gaming','video games','play','controller','nintendo'],
  '🕹️': ['gaming','joystick','arcade','retro','games'],
  '🎲': ['dice','game','roll','dungeons','dragons','board game'],
  '♟️': ['chess','piece','game','strategy','pawn'],
  '🎰': ['slot','machine','casino','vegas','gamble'],
  '🏆': ['trophy','win','champion','award','winner','medal'],
  '🥇': ['gold','medal','first place','winner','champion'],
  '🥈': ['silver','medal','second place','winner'],
  '🥉': ['bronze','medal','third place','winner'],
  '🎁': ['gift','present','birthday','wrapped','box','christmas'],
  '🎀': ['ribbon','bow','gift','pink','cute','celebration'],
  '🎈': ['balloon','party','birthday','balloons','celebration'],
  '🎊': ['confetti','ball','party','celebrate','birthday'],
  '🎉': ['party','confetti','celebrate','birthday','tada'],
  '🎎': ['japanese','doll','festival',' decoration'],
  '🎐': ['wind chime','bell','japan',' decoration'],
  '🏮': ['lantern','japanese','light','red','izakaya'],
  '❤️‍🔥': ['heart','fire','love','passion','hot','flames'],
  '💌': ['love','letter','romantic','envelope','note'],
  '💬': ['speech','bubble','chat','talk','comment'],
  '💭': ['thought','bubble','thinking','thoughts','wondering'],
  '👀': ['eyes','look','see','watch','looking','staring'],
  '👁️': ['eye','look','see','watch','single eye'],
  '🫶': ['thanks','appreciation','high five','respect','grateful'],
  '🙌': ['hands','celebrate','praise','high five','hands up'],
  '👏': ['clap','applause','clapping','bravo','yay'],
  '🤝': ['handshake','deal','agree','partnership','shake'],
  '👍': ['like','thumbs up','ok','yes','good','approve'],
  '👎': ['dislike','thumbs down','bad','no','reject'],
  '✊': ['fist','punch','power','rock','resist','raise'],
  '👊': ['fist','punch','hit','slap','fight'],
  '💪': ['muscle','strong','flex','bicep','workout','power'],
  '🤙': ['call','shaka','hang loose','phone','sign','hello'],
  '👋': ['wave','waving','hello','hi','bye','hand'],
  '🤚': ['hand','stop','palm','stop','raised'],
  '✋': ['hand','stop','high five','palm','raised'],
  '🖖': ['vulcan','spock','star trek','live long',' salute'],
  '👌': ['ok','perfect','good','nice','a-ok'],
  '🤌': ['pinched','italian','fingers','gesture','italy'],
  '🤏': ['pinching','tiny','small','pinch'],
  '✌️': ['peace','victory','v','two','胜利'],
  '🤞': ['crossed','fingers','hope','lucky','crossed'],
  '🤟': ['love','you','rock on','horns','gesture','rock'],
  '🤘': ['rock','horns','metal','rock on','sign','rock'],
  '💅': ['nail','manicure','fabulous','self care',' makeup'],
  '🤳': ['selfie','camera','phone','self portrait','self'],
  '🦾': ['robot','arm','mechanical','prosthetic'],
  '🧠': ['brain','smart','think','intelligence','clever'],
  '👑': ['crown','king','queen','royalty','gold','win'],
  '💎': ['gem','diamond','jewel','precious','rich','bling'],
  '🔮': ['crystal ball','magic','future','fortune','mystic'],
  '🧿': ['nazar','evil eye','amulet','turkish','protection'],
  '💈': ['barber','pole','salon','haircut','shops'],
  '🎭': ['masks','theatre','drama','comedy','tragedy','acting'],
  '🎨': ['art','palette','painting','colorful','creative'],
  '🎬': ['movie','clapper','film','cinema','hollywood','action'],
  '🎤': ['microphone','mic','sing','karaoke','music','podcast'],
  '🎧': ['headphones','music','listen','audio','beats'],
  '🎸': ['guitar','music','rock','band','instrument','strings'],
  '🥁': ['drum','music','drums','band','beat'],
  '🎺': ['trumpet','music','brass','jazz','band'],
  '🎷': ['saxophone','music','jazz','brass','band'],
  '🎻': ['violin','music','classical','strings','orchestra'],
  '🎹': ['piano','music','keys','keyboard','instrument'],
  '💳': ['credit card','payment','buy','shop','bank','card'],
  '💰': ['money','bag','cash','rich','dollar','money bag'],
  '🪙': ['coin','money','gold','currency','penny'],
  '💵': ['money','dollar','cash','bill','currency'],
  '🌹': ['flower','rose','love','romantic','red rose'],
  '🌸': ['flower','cherry blossom','spring','japan','pink'],
  '🌺': ['flower','hibiscus','tropical','hawaii','pink'],
  '🌻': ['flower','sunflower','yellow','sun','plant'],
  '🌷': ['flower','tulip','spring','pink','bloom','garden'],
  '💐': ['flowers','bouquet','gift','celebration','flowers'],
  '🍀': ['clover','luck','four leaf','irish','lucky'],
  '🌿': ['plant','leaf','grass','nature','green','herb'],
  '🌵': ['cactus','plant','desert','succulent','green'],
  '🌴': ['palm tree','tropical','beach','coconut','tree'],
  '🌲': ['tree','pine','nature','forest','christmas'],
  '🌳': ['tree','nature','plant','forest','fall'],
  '🍎': ['apple','fruit','red','healthy','food'],
  '🍐': ['pear','fruit','food','nature'],
  '🍊': ['orange','fruit','citrus','food','tangerine'],
  '🍋': ['lemon','fruit','sour','citrus','food','yellow'],
  '🍌': ['banana','fruit','yellow','food','tropical'],
  '🍉': ['watermelon','fruit','summer','pink','food'],
  '🍇': ['grapes','fruit','wine','food','purple'],
  '🍓': ['strawberry','fruit','red','food','berry'],
  '🍒': ['cherries','fruit','red','food','summer'],
  '🍑': ['peach','fruit','food','pink','summer'],
  '🍍': ['pineapple','fruit','tropical','summer','food'],
  '🥭': ['mango','fruit','tropical','food','sweet'],
  '🥥': ['coconut','fruit','tropical','milk','food'],
  '🥝': ['kiwi','fruit','green','food','tropical'],
  '🍅': ['tomato','vegetable','red','food','pasta'],
  '🌽': ['corn','vegetable','food','cob','yellow'],
  '🥕': ['carrot','vegetable','orange','food','bunny'],
  '🥦': ['broccoli','vegetable','green','healthy','food'],
  '🍕': ['pizza','food','italian','slice','cheese','pepperoni'],
  '🍔': ['burger','food','hamburger','fast food','yummy'],
  '🌮': ['taco','food','mexican','tuesday','taco','🌮'],
  '🌯': ['wrap','food','burrito','mexican','sandwich'],
  '🍜': ['noodles','ramen','food','soup','japanese','noodle'],
  '🍝': ['pasta','spaghetti','food','italian','noodle'],
  '🍣': ['sushi','food','japanese','fish','raw','sushi'],
  '🍱': ['bento','food','japanese','lunch','box'],
  '🍩': ['donut','food','dessert','sweet','doughnut'],
  '🍪': ['cookie','food','dessert','sweet','chocolate chip'],
  '🍰': ['cake','food','dessert','sweet','birthday','celebration'],
  '🎂': ['cake','birthday','food','dessert','candle','celebration'],
  '🍦': ['ice cream','dessert','food','cone','summer','cold'],
  '🧁': ['cupcake','dessert','food','sweet','baked'],
  '🍫': ['chocolate','candy','dessert','sweet','food','bar'],
  '🍬': ['candy','sweet','dessert','food','lollipop'],
  '🍭': ['lollipop','candy','sweet','dessert','food'],
  '☕': ['coffee','drink','cafe','morning','hot','espresso'],
  '🍵': ['tea','drink','green tea','japanese','hot'],
  '🍺': ['beer','drink','alcohol','cheers','pub'],
  '🍻': ['beer','drink','cheers','mug','prosit','prost'],
  '🥂': ['champagne','drink','cheers','celebration','toast'],
  '🍷': ['wine','drink','alcohol','bar','vineyard'],
  '🥃': ['whisky','drink','alcohol','glass','rocks'],
  '🍾': ['champagne','drink','celebration','pop','party'],
  '🌍': ['globe','earth','world','planet','nature'],
  '🌎': ['globe','earth','world','americas','planet'],
  '🌏': ['globe','earth','world','asia','planet'],
  '🌕': ['moon','full','full moon','night','luna'],
  '🌚': ['moon','new moon','dark','night','face'],
  '🌝': ['moon','full','face','full moon','man in the moon'],
  '🌞': ['sun','sunny','day','sunshine','morning'],
  '🌤️': ['sun','cloud','partly cloudy','weather'],
  '⛅': ['sun','cloud','weather','partly cloudy'],
  '🌧️': ['rain','weather','cloud','precipitation','wet'],
  '⛈️': ['storm','thunder','lightning','weather','rain'],
  '❄️': ['snow','snowflake','cold','winter','ice','❄️'],
  '☃️': ['snowman','winter','snow','cold','christmas'],
  '⛄': ['snowman','winter','snow','cold','built'],
  '🌪️': ['tornado','storm','wind','weather','twister'],
  '🌈': ['rainbow','pride','colorful','after rain','LGBT'],
  '💨': ['wind','whoosh','fast','blowing','dash'],
  '🌊': ['wave','ocean','beach','sea','water','surf'],
  '🔥': ['fire','hot','flame','lit','lit'],
  '💧': ['water','drop','droplet','wet','liquid'],
  '👶': ['baby','child','infant','newborn','cute'],
  '👦': ['boy','child','kid','young','male'],
  '👧': ['girl','child','kid','young','female'],
  '🧑': ['person','adult','human','neutral'],
  '👨': ['man','male','person','adult','father'],
  '👩': ['woman','female','person','adult','mother'],
  '👴': ['old man','elder','grandpa','senior','man'],
  '👵': ['old woman','elder','grandma','senior','woman'],
  '🐶': ['dog','puppy','pet','cute','canine'],
  '🐱': ['cat','kitten','pet','cute','feline'],
  '🐭': ['mouse','rodent','small','cute','cheese'],
  '🐹': ['hamster','pet','cute','small','rodent'],
  '🐰': ['rabbit','bunny','pet','cute','hop'],
  '🦊': ['fox','clever','cute','animal','manga'],
  '🐻': ['bear','animal','teddy','cute','wild'],
  '🐼': ['panda','bear','cute','bamboo','endangered'],
  '🐨': ['koala','bear','australia','cute','eucalyptus'],
  '🦁': ['lion','cat','king','wild','animal'],
  '🐯': ['tiger','cat','wild','big cat','feral'],
  '🐮': ['cow','animal','farm','moo','bovine'],
  '🐷': ['pig','animal','farm','pink','oink'],
  '🐸': ['frog','animal','toad','cute','hop'],
  '🐵': ['monkey','animal','banana','primate','ape'],
  '🦄': ['unicorn','magic','horse','fantasy','cute'],
  '🐔': ['chicken','bird','farm','hen','poultry'],
  '🐧': ['penguin','bird','cold','cute','arctic'],
  '🐦': ['bird','animal','flying','tweet','birdie'],
  '🐤': ['chick','baby chicken','bird','cute','hatching'],
  '🦆': ['duck','bird','water','quack','bath'],
  '🦅': ['eagle','bird','freedom','wing','predator'],
  '🦉': ['owl','bird','night','wise','hoot'],
  '🦇': ['bat','animal','night','flying','vampire'],
  '🐺': ['wolf','animal','wild','howl','canine'],
  '🐗': ['boar','pig','wild','animal','tusks'],
  '🐴': ['horse','animal','stallion','pony','equestrian'],
  '🦄': ['unicorn','fantasy','magic','horse','rainbow'],
  '🐝': ['bee','insect','honey','busy','stinging'],
  '🦋': ['butterfly','insect','cute','colorful','metamorphosis'],
  '🐌': ['snail','slow','mollusk','garden','cute'],
  '🐞': ['ladybug','insect','beetle','lucky','spot'],
  '🐜': ['ant','insect','bug','colony','tiny'],
  '🕷️': ['spider','insect','web','eight legs'],
  '🦂': ['scorpion','arachnid','desert','danger','sting'],
  '🐢': ['turtle','slow','reptile','shell','ocean'],
  '🐍': ['snake','reptile','hiss','slither','danger'],
  '🦎': ['lizard','reptile','gecko','salamander','cold-blooded'],
  '🦖': ['dinosaur','t-rex','extinct','tyrannosaurus','Jurassic'],
  '🦕': ['dinosaur','brontosaurus','extinct','long neck','Jurassic'],
  '🐙': ['octopus','sea','ocean','tentacles','creature'],
  '🦑': ['squid','sea','ocean','tentacles','creature'],
  '🦐': ['shrimp','sea','food','crustacean','ocean'],
  '🦀': ['crab','sea','beach','claw','crustacean'],
  '🐠': ['fish','sea','tropical','ocean','aquarium'],
  '🐟': ['fish','sea','swimming','ocean','fishing'],
  '🐬': ['dolphin','sea','ocean','smart','cute','friendly'],
  '🐳': ['whale','sea','ocean','big','blue'],
  '🦈': ['shark','sea','ocean','teeth','danger','fin'],
  '🐊': ['crocodile','reptile','teeth','wild','river'],
  '🦣': ['mammoth','extinct','woolly','ice age','tusk'],
  '🦓': ['zebra','animal','stripes','africa','wild'],
  '🦍': ['gorilla','ape','primate','wild','strong'],
  '🐘': ['elephant','animal','big','trunk','wild'],
  '🦛': ['hippo','animal','big','river','heavy'],
  '🦏': ['rhino','animal','horn','wild','africa'],
  '🐪': ['camel','animal','desert','hump','hot'],
  '🦒': ['giraffe','animal','tall','neck','africa'],
  '🦬': ['bison','animal','buffalo','wild','horns'],
  '🐃': ['water buffalo','animal','ox','farm','bovine'],
  '🐄': ['cow','bovine','milk','farm','moo'],
  '🐎': ['horse','equestrian','fast','ride','speed'],
  '🐖': ['pig','animal','pink','farm','oink'],
  '🐏': ['ram','sheep','animal','horns','farm'],
  '🐑': ['sheep','animal','wool','farm','fluffy'],
  '🦙': ['llama','animal','cute','and','south america'],
  '🐐': ['goat','animal','farm','kid'],
  '🦌': ['deer','animal','antlers','forest','elegant'],
  '🐕': ['dog','canine','pet','playful','loyal'],
  '🐩': ['poodle','dog','fancy','curly','dog breed'],
  '🦮': ['guide dog','dog','service','blind','loyal'],
  '🐈': ['cat','feline','pet','sleepy','meow'],
  '🐓': ['rooster','chicken','farm','cockadoodledoo'],
  '🦃': ['turkey','bird','thanksgiving','food','gobble'],
  '🦚': ['peacock','bird','colorful','display','proud'],
  '🦜': ['parrot','bird','tropical','colorful','mimic'],
  '🕊️': ['dove','bird','peace','flight','symbol'],
  '🐇': ['rabbit','bunny','pet','cute','hop','fluffy'],
  '🦝': ['raccoon','animal','masked','cute','trash panda'],
  '🦨': ['skunk','animal','stink','smell','stripes'],
  '🦡': ['badger','animal','furry','hibernate'],
  '🦦': ['otter','animal','cute','playful','water','river'],
  '🦥': ['sloth','animal','slow','cute','tree'],
  '🐿️': ['chipmunk','animal','squirrel','striped','cute','nut'],
  '🦔': ['hedgehog','animal','cute','small','spiky'],
  '🌵': ['cactus','desert','plant','sharp','spiky'],
  '🎄': ['christmas tree','tree','holiday','christmas','decorated'],
  '🌲': ['tree','pine','forest','nature','evergreen'],
  '🌳': ['tree','deciduous','forest','nature','leafy'],
  '🌴': ['palm tree','tree','tropical','island','vacation'],
  '🪵': ['wood','log','lumber','firewood','timber'],
  '🌱': ['seedling','plant','new','grow','spring'],
  '🌿': ['herb','plant','green','natural'],
  '☘️': ['clover','shamrock','irish','ireland','lucky'],
  '🍃': ['leaf','nature','green','fall','blowing'],
  '🍂': ['fallen leaf','leaf','autumn','fall','orange'],
  '🍁': ['maple leaf','leaf','canada','autumn','fall'],
  '🪹': ['nest','bird','eggs','hatching','nursery'],
  '🍄': ['mushroom','fungus','nature','super mario','edible'],
  '🌾': ['ear of rice','plant','agriculture','field','harvest'],
  '🪴': ['potted plant','plant','flower','green','indoor'],
  '🎋': ['tanabata tree','japanese','festival','decoration'],
  '🎍': ['kadomatsu','japanese','decoration','new year'],
  '☀️': ['sun','sunny','day','bright','hot','weather'],
  '🌤️': ['sun','behind cloud','weather','partly sunny'],
  '🌥️': ['sun','cloud','weather','mostly cloudy'],
  '☁️': ['cloud','cloudy','overcast','weather'],
  '🌦️': ['sun','rain','weather','partly sunny with rain'],
  '🌧️': ['rain','weather','cloud','precipitation','wet'],
  '🌩️': ['lightning','storm','weather','thunder'],
  '🌨️': ['snow','weather','cloud','cold','precipitation'],
  '🌀': ['cyclone','hurricane','storm','spin','tornado'],
  '🌪️': ['tornado','storm','wind','weather','twister'],
  '🌫️': ['fog','mist','weather','cloudy','hazy'],
  '🌬️': ['wind','blowing','air','weather','breeze'],
  '💨': ['wind','fast','dash','whoosh','blowing'],
  '🪐': ['planet','saturn','space','rings','cosmic'],
  '🚀': ['rocket','space','launch','nasa','fast','ship'],
  '🛸': ['ufo','alien','spaceship','flying saucer','extraterrestrial'],
  '⛵': ['ship','boat','vessel','sail','cruise'],
  '✈️': ['plane','airplane','travel','flight','fly','aircraft'],
  '🚁': ['helicopter','flying','copter','rescue','transport'],
  '🚂': ['train','locomotive','steam engine','railway'],
  '🚃': ['train','railway','car','transport'],
  '🚗': ['car','automobile','vehicle','drive','red'],
  '🚕': ['taxi','car','uber','ride','vehicle'],
  '🚙': ['suv','car','vehicle','off road','jeep'],
  '🚌': ['bus','vehicle','public','transport','ride'],
  '🚑': ['ambulance','vehicle','medical','emergency','hospital'],
  '🚒': ['fire truck','vehicle','fire','emergency','rescue'],
  '🚓': ['police car','vehicle','cop','law','chase'],
  '🏎️': ['race car','car','formula','racing','fast'],
  '🏍️': ['motorcycle','bike','ride','speed','hobby'],
  '🛵': ['scooter','vespa','bike','ride','motor'],
  '🚲': ['bicycle','bike','cycle','eco','transport','exercise'],
  '⛵': ['sailboat','boat','sailing','sea','naval'],
  '🚤': ['speedboat','boat','speed','sea','fast'],
  '🛥️': ['motorboat','boat','engine','sea','water'],
  '🚢': ['ship','boat','cruise','sailing','titanic'],
  '✉️': ['envelope','letter','mail','post','email'],
  '📧': ['e-mail','email','letter','internet','mail'],
  '💌': ['love letter','letter','romantic','note','heart'],
  '📩': ['envelope','letter','hand','mail','send'],
  '📨': ['incoming','letter','arrive','receive','mail'],
  '📯': ['postal horn','horn','mail','post','notification'],
  '📦': ['box','package','delivery','shipping','amazon'],
  '📫': ['mailbox','post','flag','flag is up','postal'],
  '📬': ['mailbox','flag is up','receive','postal','mail'],
  '📮': ['post office','postal','mail','building'],
  '📁': ['folder','file','category','organize','dir'],
  '📂': ['open folder','file','directory','organize'],
  '📃': ['document','page','paper','text','script'],
  '📄': ['page','document','paper','text','letter'],
  '📑': ['bookmark tabs','document','tabs','organize'],
  '📰': ['newspaper','news','press','media','read'],
  '📓': ['notebook','journal','write','note','study'],
  '📔': ['notebook','decorative','diary','write'],
  '📒': ['ledger','notebook','accounting','business'],
  '📕': ['book','closed','read','red'],
  '📗': ['book','green','closed','study','read'],
  '📘': ['book','blue','closed','study','read'],
  '📙': ['book','orange','closed','read','study'],
  '📚': ['books','books','read','study','library','stack'],
  '📖': ['open book','read','study','book','page'],
  '🔖': ['bookmark','label','marker','save','index'],
  '🔗': ['link','chain','hyperlink','connect','url'],
  '📎': ['paperclip','office','stationery','clip'],
  '🖇️': ['linked paperclips','paperclips','office','chain'],
  '📌': ['pushpin','pin','location','map','red'],
  '📍': ['round pushpin','pin','location','map','red'],
  '📏': ['straight ruler','ruler','measure','straight','office'],
  '📐': ['triangular ruler','ruler','angle','measure','drafting'],
  '📒': ['notebook','ledger','accounting','business'],
  '📊': ['chart','bar chart','graph','statistics','business'],
  '📈': ['chart','graph','up','trend','growth','increase'],
  '📉': ['chart','graph','down','trend','decline','decrease'],
  '📆': ['tear-off calenda','date','day','calendar','schedule'],
  '📅': ['calendar','date','day','schedule','planner'],
  '📇': ['card index','index','organize',' rolodex'],
  '🗃️': ['card file box','file','organize','database'],
  '🗳️': ['ballot box','vote','election','ballot','ballot box'],
  '🗄️': ['file cabinet','cabinet','file','storage','office'],
  '📋': ['clipboard','board','write','note','checklist'],
  '🔍': ['magnifying','glass left','search','look','find','hunt'],
  '🔎': ['magnifying','glass right','search','look','find','hunt'],
  '🔏': ['pencil','and lock','write','edit','private','secure'],
  '🔐': ['lock','with key','locked','secure','secret'],
  '🔑': ['key','lock','unlock','home','passage'],
  '🗝️': ['old key','key','retro','vintage','lock'],
  '🧰': ['toolbox','tools','repair','wrench','hammer','fix'],
  '🔧': ['wrench','tool','fix','mechanic','repair'],
  '🔨': ['hammer','tool','build','hit','nail','construction'],
  '⚒️': ['hammer','pick','tools','mining','minecraft'],
  '🛠️': ['hammer','wrench','tools','repair','fix'],
  '⛏️': ['pick','tool','mine','mining','break'],
  '🔩': ['nut','bolt','hardware','mechanic'],
  '⚙️': ['gear','settings','cog','engineering','machine'],
  '🪤': ['mousetrap','trap','mouse','cheese','catch'],
  '🧱': ['brick','wall','construction','building','minecraft'],
  '⛓️': ['chains','chain','link','connection','locked'],
  '🧲': ['magnet','attraction','magnetic','stick','refrigerator'],
  '🔫': ['water gun','toy','gun','squirt','water','play'],
  '💣': ['bomb','explosive','destructible','boom'],
  '🧨': ['firecracker','explosive','celebration','noise','fire'],
  '🪓': ['axe','wood','chop','weapon','viking','wilderness'],
  '🔪': ['knife','kitchen','cut','weapon','chef'],
  '🗡️': ['dagger','weapon','sword','knife','fight'],
  '⚔️': ['swords','crossed','fight','battle','duel','war'],
  '🛡️': ['shield','defense','protect','medieval','armor'],
  '🚬': ['cigarette','smoking','tobacco','cigar','bad habit'],
  '⚰️': ['coffin','death','funeral','burial','halloween'],
  '🪦': ['headstone','grave','tomb','rest','peace'],
  '⚱️': ['urn','funeral','ash','burial','cremation'],
  '🏺': ['amphora','jar','roman','vase','ancient'],
  '🔭': ['telescope','space','astronomy','stars','night'],
  '🔬': ['microscope','science','research','tiny','cell'],
  '🕳️': ['hole','pit','opening','tunnel','void'],
  '🩹': ['adhesive bandage','bandage','heal','wound','medical'],
  '🩺': ['stethoscope','medical','doctor','heart','health'],
  '💊': ['pill','medicine','drug','health','capsule'],
  '💉': ['syringe','vaccine','injection','medical','blood'],
  '🩸': ['blood','drop','health','donate','type'],
  '🧬': ['dna','genetics','science','helix','biology'],
  '🦠': ['virus','covid','bacteria','germ','sick','microbe'],
  '🧫': ['petri dish','science','bacteria','lab','culture'],
  '🧪': ['test tube','science','experiment','chemistry','lab'],
  '🌡️': ['thermometer','temperature','fever','weather','hot'],
  '🧹': ['broom','clean','sweep','witch','magic'],
  '🪠': ['plunger','toilet','unclog','bathroom','clear'],
  '🧺': ['basket','laundry','clothes','wash','hamper'],
  '🧻': ['toilet roll','paper','bathroom','flush','tp'],
  '🚽': ['toilet','bathroom','potty','restroom','flush'],
  '🚰': ['potable water','water','drink','tap','faucet'],
  '🚿': ['shower','bathroom','wash','bath','water'],
  '🛁': ['bathtub','bath','bubble','bathroom','soak'],
  '🛀': ['bath','person','relax','bubble','spa'],
  '🧼': ['soap','wash','clean','bubble','dish','sponge'],
  '🪥': ['toothbrush','teeth','dental','hygiene','brush'],
  '🪒': ['razor','shave','groom','beard','blade'],
  '🧽': ['sponge','clean','wash','kitchen','dishes'],
  '🪣': ['bucket','water','carry','pail','clean'],
  '🧴': ['lotion bottle','lotion','sunscreen','moisturizer','skincare'],
  '🛎️': ['bell','door','hotel','service','reception'],
  '🚪': ['door','room','entrance','exit','open'],
  '🪑': ['chair','seat','sit','furniture','office'],
  '🛋️': ['couch','sofa','sit','living room','relax'],
  '🛏️': ['bed','sleep','rest','bedroom','sleeping'],
  '🛌': ['bed','sleeping','person','tired','rest'],
  '🧸': ['teddy bear','bear','toy','cute','plush','child'],
  '🪆': ['nesting dolls','russian doll','matryoshka','toy','cute'],
  '🖼️': ['frame','picture','photo','art','painting'],
  '🪞': ['mirror','reflect','vanity','glass','look'],
  '🪟': ['window','curtain','home','glass','frame'],
  '🛍️': ['shopping bags','bags','shopping','buy','mall','retail'],
  '🛒': ['shopping cart','cart','buy','grocery','mall','shop'],
  '⌚': ['watch','time','clock','wearable','wrist'],
  '📱': ['phone','mobile','cell','smartphone','call','text'],
  '📲': ['phone','incoming','call','mobile','received'],
  '💻': ['laptop','computer','mac','macbook','screen','code'],
  '⌨️': ['keyboard','computer','type','code','mac','input'],
  '🖥️': ['monitor','computer','display','screen','desktop'],
  '🖨️': ['printer','computer','print','paper','office'],
  '🖱️': ['mouse','computer','click','office','cursor'],
  '🖲️': ['trackball','computer','mouse','ball','office'],
  '💽': ['minidisc','disk','storage','computer','disc'],
  '💾': ['floppy disk','disk','save','retro','old school'],
  '💿': ['cd','disc','dvd','cd-rom','storage','music'],
  '📀': ['dvd','disc','movie','video','disk'],
  '📼': ['video tape','vhs','tape','retro','vintage','movie'],
  '📷': ['camera','photo','picture','dslr','capture'],
  '📸': ['camera','flash','photo','picture','capture'],
  '📹': ['video camera','video','film','record','movie'],
  '🎥': ['movie camera','video','film','cinema','record'],
  '📽️': ['film projector','projector','movie','cinema','retro'],
  '🎞️': ['film frames','movie','film','photo','cinema'],
  '📞': ['receiver','telephone','phone','old','ring'],
  '☎️': ['phone','telephone','ring','call','retro'],
  '📟': ['pager','beeper','retro','90s','message'],
  '📠': ['fax','machine','office','retro','send'],
  '📺': ['tv','television','watch','screen','shows'],
  '📻': ['radio','music','listen','broadcast','am fm'],
  '🎙️': ['studio microphone','mic','podcast','studio','broadcast'],
  '🎚️': ['slider','audio','mixing','levels','music'],
  '🎛️': ['dial','knobs','audio','settings','control'],
  '🧭': ['compass','direction','navigate','travel','map'],
  '⏱️': ['stopwatch','time','timer','clock','record'],
  '⏲️': ['timer','clock','countdown','egg','cooking'],
  '🕰️': ['mantelpiece clock','clock','retro','decorative'],
  '⏰': ['alarm clock','alarm','morning','wake','clock'],
  '⌛': ['hourglass','time','wait','sand','clock'],
  '⏳': ['hourglass','time','wait','sand','loading'],
  '🧭': ['compass','direction','navigate','travel','explore'],
  '🔔': ['bell','ring','notification','sound','alert'],
  '📯': ['postal horn','horn','mail','post','arrival'],
  '📡': ['satellite','signal','antenna','space','communication'],
  '🔋': ['battery','power','charge','electronic','low'],
  '🔌': ['plug','electric','power','outlet','charge'],
  '💡': ['light bulb','idea','bulb','bright','thought'],
  '🔦': ['flashlight','light','torch','dark','beam'],
  '🕯️': ['candle','light','romantic','scented',' ambiance'],
  '🪔': ['diya lamp','lamp','diya','indian','prayer','oil'],
  '🧯': ['fire extinguisher','extinguisher','fire','safety','stop'],
  '🛢️': ['oil barrel','oil','barrel','fuel','drum'],
  '🔅': ['dim button','brightness','low','screen','dim'],
  '🔆': ['bright button','brightness','high','screen','bright'],
  '📴': ['mobile phone','phone','off','silent','shutdown'],
  '📳': ['vibration mode','phone','vibrate','silent','quiet'],
  '🈶': ['japanese','not free','charge','button','kanji'],
  '🈚': ['japanese','free of charge','not','button','kanji'],
  '🈸': ['japanese','application','form','request','kanji'],
  '🈺': ['japanese','in business','open','shop','kanji'],
  '🈷️': ['japanese','monthly amount','kanji','button'],
  '🆚': ['vs','versus','versus','versus','competition'],
  '🆕': ['new','new','newest','new','label'],
  '🆗': ['ok','okay','fine','okay','button','acceptable'],
  '🆘': ['sos','help','emergency','danger','button'],
  '🆙': ['up','up','button','up','exclamation'],
  '🆒': ['cool','cool','awesome','neat','button'],
  '🆔': ['id','identity','card','label','new'],
  '🆓': ['free','free','free','gratis','button'],
  '0️⃣': ['0','zero','number','digit','zero'],
  '1️⃣': ['1','one','number','digit','one'],
  '2️⃣': ['2','two','number','digit','two'],
  '3️⃣': ['3','three','number','digit','three'],
  '4️⃣': ['4','four','number','digit','four'],
  '5️⃣': ['5','five','number','digit','five'],
  '6️⃣': ['6','six','number','digit','six'],
  '7️⃣': ['7','seven','number','digit','seven'],
  '8️⃣': ['8','eight','number','digit','eight'],
  '9️⃣': ['9','nine','number','digit','nine'],
  '🔟': ['10','ten','number','digit','ten'],
  '🔢': ['numbers','input','123','number','digits'],
  '🔣': ['symbols','input','symbols','signs'],
  '🔤': ['alphabet','abc','letters','input','spell'],
  '🔡': ['input latin lowercase','abc','small','letters','lower'],
  '🔠': ['input latin uppercase','ABC','capital','letters','upper'],
  '🅰️': ['a','blood type','letter','type'],
  '🅱️': ['b','blood type','letter','type'],
  '🅾️': ['o','blood type','letter','type'],
  '🅿️': ['p','parking','letter','sign','p button'],
  '🆎': ['ab','blood type','letters','type'],
  '🆑': ['cl','button','clear','reset'],
  '🆒': ['cool','cool','cool','awesome'],
  '🆓': ['free','free','gratis','no charge','button'],
  '🆔': ['id','identity','identification','button'],
  '🆕': ['new','new','newest','button'],
  '🆗': ['ok','okay','okay','acceptable','button'],
  '🆘': ['sos','sos','help','emergency','button'],
  '🆙': ['up','up','exclamation','button'],
  '🆒': ['cool','cool','cool','awesome','button'],
  '🈁': ['japanese','here','kokunai','button','mark'],
  '🈂️': ['japanese','service charge','button','katakana'],
  '🈷️': ['japanese','month','button','katakana'],
  '🈶': ['japanese','not free','button','kanji'],
  '🈯': ['japanese','finger','kanji','reserved'],
  '🉐': ['japanese','bargain','exchange','button','kanji'],
  '🈹': ['japanese','discount','sale','button','kanji'],
  '🈚': ['japanese','free of charge','button','kanji'],
  '🈸': ['japanese',' application','form','button','kanji'],
  '🈺': ['japanese','in business','open','button','kanji'],
  '🈷️': ['japanese','monthly amount','monthly amount'],
  '㊙️': ['japanese','secret','private','hiddne','button'],
  '㊗️': ['japanese','congratulations','celebrate','button','kanji'],
  '🈴': ['japanese','passing','joint','together'],
  '🈵': ['japanese','no vacancy','full','closed','occupied'],
  '🈲': ['japanese','prohibited','banned','forbidden','no'],
  '🈳': ['japanese','vacancy','available','open','free'],
  '🈂️': ['japanese','service','charge','katakana'],
  '🈐': ['japanese','reserved for','specific purpose'],
  '�芷': ['japanese','this','place'],
  '🈯': ['japanese','reserved','appointed','kanji'],
  '♈': ['aries','zodiac','ram','aries','star sign'],
  '♉': ['taurus','zodiac','bull','star sign'],
  '♊': ['gemini','zodiac','twins','star sign'],
  '♋': ['cancer','zodiac','crab','star sign'],
  '♌': ['leo','zodiac','lion','star sign'],
  '♍': ['virgo','zodiac','virgin','star sign'],
  '♎': ['libra','zodiac','balance','star sign'],
  '♏': ['scorpio','zodiac','scorpion','star sign'],
  '♐': ['sagittarius','zodiac','archer','star sign'],
  '♑': ['capricorn','zodiac','sea goat','star sign'],
  '♒': ['aquarius','zodiac','water bearer','star sign'],
  '♓': ['pisces','zodiac','fish','star sign'],
  '⛎': ['ophiuchus','zodiac','serpent bearer','star sign'],
  '🛑': ['stop','sign','octagon','red','stop'],
  '⛔': ['no entry','sign','stop','prohibited','forbidden'],
  '📛': ['name badge','badge','id','lanyard','name'],
  '🔞': ['no one under eighteen','age restriction','18+','adult','nsfw'],
  '🚫': ['prohibited','no','forbidden','banned','stop'],
  '💯': ['100','hundred','perfect','score','on fire','fire'],
  '✅': ['check','done','yes','ok','complete','tick'],
  '❎': ['x','wrong','cross','no','error','cancel','close'],
  '➕': ['plus','add','more','increase','positive'],
  '➖': ['minus','subtract','take','decrease','negative'],
  '➗': ['divide','division','math','÷','calculator'],
  '✖️': ['multiply','times','×','math','multiplication'],
  '♾️': ['infinity','forever','endless','loop','symbol'],
  '➰': ['curly loop','loop','decorative','swirl','swirl'],
  '➿': ['double curly loop','loop','snare','swirl'],
  '〰️': ['wavy dash','dash','line','squiggle','decorative'],
  '💱': ['currency exchange','exchange','money','dollar',' Yen',' conversion'],
  '™️': ['trademark','brand','legal','logo','mark'],
  '©️': ['copyright','legal','c','brand'],
  '®️': ['registered','legal','r','brand'],
  '�ℹ️': ['information','info','i','help','more'],
  'Ⓜ️': ['circled','m','circled','letter','m button'],
  '🔠': ['input','latin','uppercase','AB','text','caps'],
  '🔡': ['input','latin','lowercase','ab','text','small'],
  '🔣': ['input','symbols','symbols','unicode','characters'],
  'ℹ️': ['information','info','more details','about','i'],
  '🔺': ['red triangle','triangle','up','direction','warning'],
  '🔻': ['red triangle','triangle','down','direction','warning'],
  '🔲': ['black square','square','box','geometric','shape'],
  '🔳': ['white square','square','box','border','shape'],
  '🔷': ['blue diamond','diamond','shape','geometric','blue'],
  '🔶': ['large orange diamond','diamond','shape','orange','geometric'],
  '🔷': ['large blue diamond','diamond','shape','blue','geometric'],
  '🔶': ['large orange diamond','diamond','shape','orange','geometric'],
  '🔸': ['small orange diamond','diamond','shape','orange','small'],
  '🔹': ['small blue diamond','diamond','shape','blue','small'],
  '💠': ['diamond with dot','shape','dot','inside','circle'],
  '◽': ['white medium small square','square','shape','small','light'],
  '◾': ['black medium small square','square','shape','small','dark'],
  '⬜': ['white large square','square','shape','large','empty'],
  '⬛': ['black large square','square','shape','dark','filled'],
  '🔘': ['radio button','button','select','option','choice'],
  '🔳': ['white square button','button','square','outline'],
  '🔲': ['black square button','button','square','filled'],
  '▫️': ['white small square','square','shape','small','light'],
  '▪️': ['black small square','square','shape','small','dark'],
  '🔻': ['red triangle','warning','down','arrow','direction'],
  '🔺': ['red triangle','up','arrow','direction','warning'],
  '🔈': ['speaker','sound','volume','audio','low'],
  '🔉': ['speaker','medium volume','sound','audio','medium'],
  '🔊': ['speaker','high volume','sound','audio','loud'],
  '🔇': ['muted speaker','sound','off','muted','no audio'],
  '📣': ['megaphone','announce','speaker','broadcast','hey'],
  '📢': ['loudspeaker','announce','broadcast','public','speaker'],
  '🔔': ['bell','ring','notification','sound','alert'],
  '🔕': ['bell with slash','bell','off','silent','quiet'],
  '🎵': ['musical note','music','note','beat','sound'],
  '🎶': ['musical notes','music','notes','multiple','sound'],
  '🎼': ['musical score','music','score','notes','sheet'],
  '🎤': ['microphone','mic','sing','music','podcast','vocal'],
  '🎧': ['headphones','music','listen','audio','beats','sound'],
  '🎸': ['guitar','music','rock','band','instrument','string'],
  '🎹': ['piano','music','keys','keyboard','instrument'],
  '🎷': ['saxophone','music','jazz','brass','instrument'],
  '🎺': ['trumpet','music','jazz','brass','instrument'],
  '🎻': ['violin','music','classical','instrument','orchestra'],
  '🥁': ['drum','music','beat','percussion','drums','band'],
  '🪘': ['long drum','music','beat','rhythm','instrument'],
  '🪕': ['banjo','music','string','instrument','country'],
  '🪗': ['accordion','music','instrument','piano','marching'],
  '🎲': ['dice','game','roll','random','d&d'],
  '♟️': ['chess pawn','chess','pawn','game','strategy'],
  '🎯': ['target','bullseye','dart','hit','goal'],
  '🎳': ['bowling','game','pin','sport','strike'],
  '🎮': ['gaming','video','games','play','controller','nintendo'],
  '🕹️': ['joystick','gaming','arcade','retro','games'],
  '🎰': ['slot machine','casino','vegas','gamble','lucky'],
  '🎲': ['dice','game','roll','random','chance'],
  '🧩': ['puzzle','jigsaw','game','piece','fit'],
  '♠️': ['spade','cards','suit','poker','black'],
  '♣️': ['clover','club','cards','suit','poker','black'],
  '♥️': ['hearts','cards','suit','poker','love','red'],
  '♦️': ['diamonds','cards','suit','poker','red','diamond'],
  '🃏': ['joker','cards','joker','game','wild'],
  '🎴': ['flower playing cards','cards','japanese','flower','hanafuda'],
  '🀄': ['mahjong','red dragon','game','tiles','chinese'],
  '🃏': ['joker','cards','joker','wild','game'],
  '🕐': ['clock','1','o clock','time','one'],
  '🕑': ['clock','2','o clock','time','two'],
  '🕒': ['clock','3','o clock','time','three'],
  '🕓': ['clock','4','o clock','time','four'],
  '🕔': ['clock','5','o clock','time','five'],
  '🕕': ['clock','6','o','time','six'],
  '🕖': ['clock','7','o clock','time','seven'],
  '🕗': ['clock','8','o clock','time','eight'],
  '🕘': ['clock','9','o clock','time','nine'],
  '🕙': ['clock','10','o clock','time','ten'],
  '🕚': ['clock','11','o clock','time','eleven'],
  '🕛': ['clock','12','o clock','time','twelve'],
}

const ALL_EMOJIS = Object.values(EMOJI_CATEGORIES).flat()

interface Props {
  onClose: () => void
  onInsert: (emoji: string) => void
}

export default function EmojiPicker({ onClose, onInsert }: Props) {
  const [q, setQ] = useState('')
  const inputRef = useRef<HTMLInputElement>(null)

  useEffect(() => { inputRef.current?.focus() }, [])

  const handleKeyDown = useCallback((e: React.KeyboardEvent) => {
    if (e.key === 'Escape') onClose()
  }, [onClose])

  const filtered = q.trim()
    ? ALL_EMOJIS.filter((e) => EMOJI_KEYWORDS[e]?.some(k => k.includes(q.toLowerCase())))
    : null

  return (
    <div
      className="absolute bottom-calc(100% + 8px) z-50 bg-bg-panel border border-border-md rounded-card shadow-2xl w-80 overflow-hidden"
      style={{ bottom: 'calc(100% + 8px)', left: '0' }}
    >
      <div className="p-2 border-b border-border-lo">
        <input
          ref={inputRef}
          value={q}
          onChange={(e) => setQ(e.target.value)}
          onKeyDown={handleKeyDown}
          placeholder="Search emojis..."
          className="input-field text-sm"
        />
      </div>
      <div className="max-h-64 overflow-y-auto p-2">
        {filtered ? (
          <div className="grid grid-cols-8 gap-0.5">
            {filtered.map((e) => (
              <button
                key={e}
                onClick={() => onInsert(e)}
                className="w-8 h-8 flex items-center justify-center text-lg rounded hover:bg-bg-hover transition-colors"
              >
                {e}
              </button>
            ))}
            {filtered.length === 0 && (
              <div className="col-span-8 text-center text-text-lo text-xs py-4">No emojis found</div>
            )}
          </div>
        ) : (
          Object.entries(EMOJI_CATEGORIES).map(([cat, emojis]) => (
            <div key={cat} className="mb-3">
              <p className="text-text-lo text-xs font-body uppercase tracking-wider mb-1 px-1">{cat}</p>
              <div className="grid grid-cols-8 gap-0.5">
                {emojis.map((e) => (
                  <button
                    key={e}
                    onClick={() => onInsert(e)}
                    className="w-8 h-8 flex items-center justify-center text-lg rounded hover:bg-bg-hover transition-colors"
                    title={e}
                  >
                    {e}
                  </button>
                ))}
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  )
}

export function insertEmoji(textarea: HTMLTextAreaElement | null, emoji: string) {
  if (!textarea) return
  const nativeInputValueSetter = Object.getOwnPropertyDescriptor(window.HTMLTextAreaElement.prototype, 'value')?.set
  const start = textarea.selectionStart
  const end = textarea.selectionEnd
  const val = textarea.value
  const next = val.slice(0, start) + emoji + val.slice(end)
  nativeInputValueSetter?.call(textarea, next)
  textarea.dispatchEvent(new Event('input', { bubbles: true }))
  textarea.selectionStart = textarea.selectionEnd = start + emoji.length
}